"""Pydantic schemas for request/response models and internal data types."""

from __future__ import annotations

from datetime import datetime
from enum import Enum
from uuid import uuid4

from pydantic import BaseModel, Field


# ---------------------------------------------------------------------------
# Enums
# ---------------------------------------------------------------------------
class AgentRole(str, Enum):
    """Identifiers for each agent in the research pipeline."""

    SUPERVISOR = "supervisor"
    RESEARCHER = "researcher"
    WRITER = "writer"


class SessionStatus(str, Enum):
    """Lifecycle states for a research session."""

    PENDING = "pending"
    RESEARCHING = "researching"
    WRITING = "writing"
    COMPLETED = "completed"
    FAILED = "failed"


# ---------------------------------------------------------------------------
# Request Models
# ---------------------------------------------------------------------------
class ResearchRequest(BaseModel):
    """Incoming request to start a research session."""

    topic: str = Field(..., min_length=3, max_length=500, description="Research topic")
    depth: str = Field(
        default="standard",
        description="Research depth: 'quick', 'standard', or 'deep'",
    )
    max_sources: int = Field(default=5, ge=1, le=15, description="Max web sources")


# ---------------------------------------------------------------------------
# Response Models
# ---------------------------------------------------------------------------
class SourceInfo(BaseModel):
    """A single source used in the research report."""

    title: str
    url: str
    snippet: str = ""
    relevance_score: float = 0.0


class ResearchReport(BaseModel):
    """The final research report generated by the writer agent."""

    title: str = ""
    summary: str = ""
    key_findings: list[str] = Field(default_factory=list)
    detailed_analysis: str = ""
    sources: list[SourceInfo] = Field(default_factory=list)
    generated_at: datetime = Field(default_factory=datetime.utcnow)


class ResearchSession(BaseModel):
    """Full state of a research session returned to the frontend."""

    session_id: str = Field(default_factory=lambda: uuid4().hex[:12])
    topic: str
    status: SessionStatus = SessionStatus.PENDING
    report: ResearchReport | None = None
    sources_found: int = 0
    chunks_stored: int = 0
    created_at: datetime = Field(default_factory=datetime.utcnow)


# ---------------------------------------------------------------------------
# WebSocket Event Models
# ---------------------------------------------------------------------------
class WSEvent(BaseModel):
    """A single WebSocket event streamed to the frontend."""

    event: str  # e.g. "agent_start", "tool_call", "status", "report", "error"
    agent: str = ""
    data: dict = Field(default_factory=dict)
    timestamp: datetime = Field(default_factory=datetime.utcnow)
