"""Report generation tool.

Provides a structured template for the writer agent to produce
well-formatted Markdown research reports.
"""

from __future__ import annotations

from langchain_core.tools import tool


@tool
def generate_report(
    title: str,
    summary: str,
    key_findings: str,
    detailed_analysis: str,
    sources_text: str,
) -> str:
    """Generate a structured Markdown research report.

    Takes the components of a research report and assembles them into
    a clean, well-formatted Markdown document.

    Args:
        title: Report title.
        summary: Executive summary (2-3 paragraphs).
        key_findings: Key findings as a numbered list.
        detailed_analysis: In-depth analysis section.
        sources_text: Formatted list of sources with URLs.

    Returns:
        Complete Markdown research report.
    """
    report = f"""# {title}

## Executive Summary

{summary}

## Key Findings

{key_findings}

## Detailed Analysis

{detailed_analysis}

## Sources & References

{sources_text}

---
*Report generated by AI Research Agent*
"""
    return report.strip()
