"""Writer agent node.

The writer synthesizes all research gathered in the ChromaDB vector
store into a structured, well-cited Markdown report.
"""

from __future__ import annotations

import logging

from langchain_core.messages import AIMessage, HumanMessage, SystemMessage
from langchain_google_genai import ChatGoogleGenerativeAI

from app.agents.state import AgentState
from app.config import GEMINI_MODEL, GOOGLE_API_KEY, RAG_TOP_K
from app.rag.vectorstore import similarity_search

logger = logging.getLogger(__name__)

WRITER_SYSTEM_PROMPT = """\
You are the Writer Agent in a multi-agent research system. Your job is
to synthesize research findings into a comprehensive, well-structured
Markdown report.

## Report Structure
Your report MUST follow this exact structure:

# [Title reflecting the research topic]

## Executive Summary
A concise 2-3 paragraph overview of the research findings.

## Key Findings
A numbered list of the 5-8 most important findings.

## Detailed Analysis
In-depth discussion organized into logical subsections with ### headers.
Include specific data points, quotes, and analysis.

## Sources & References
A numbered list of all sources used, with titles and URLs.

---
*Report generated by AI Research Agent*

## Instructions
1. Use ONLY information from the provided research context below.
2. Cite sources using [Source N] notation inline.
3. Be factual and objective — do not speculate.
4. Make the report comprehensive yet readable.
5. Include specific data points and quotes where available.
"""


def writer_node(state: AgentState) -> dict:
    """Writer agent node — synthesizes research into a Markdown report.

    Queries the RAG store for all relevant context and uses the LLM
    to compose a structured research report.
    """
    topic = state.get("research_topic", "")
    session_id = state.get("session_id", "")

    try:
        # Retrieve all relevant context from the vector store
        # Use multiple queries to get broad coverage
        queries = [
            topic,
            f"key findings about {topic}",
            f"detailed information on {topic}",
            f"statistics and data about {topic}",
        ]

        all_contexts: list[str] = []
        seen_contents: set[str] = set()
        source_list: list[dict] = []

        for query in queries:
            results = similarity_search(session_id, query, top_k=RAG_TOP_K)
            for doc in results:
                # Deduplicate by content hash
                content_hash = doc.page_content[:100]
                if content_hash not in seen_contents:
                    seen_contents.add(content_hash)
                    source = doc.metadata.get("source", "Unknown")
                    title = doc.metadata.get("title", "")

                    all_contexts.append(
                        f"[Source: {title or source}]\n{doc.page_content}"
                    )
                    source_list.append({
                        "title": title,
                        "url": source,
                        "snippet": doc.page_content[:200],
                    })

        if not all_contexts:
            return {
                "messages": [AIMessage(
                    content="[Writer] No research context available. Cannot generate report."
                )],
                "report": "# Research Report\n\nInsufficient data gathered during research phase.",
                "current_agent": "supervisor",
            }

        # Compose the report using the LLM
        context_block = "\n\n---\n\n".join(all_contexts[:20])  # Cap at 20 chunks

        llm = ChatGoogleGenerativeAI(
            model=GEMINI_MODEL,
            google_api_key=GOOGLE_API_KEY,
            temperature=0.4,
        )

        response = llm.invoke([
            SystemMessage(content=WRITER_SYSTEM_PROMPT),
            HumanMessage(
                content=(
                    f"## Research Topic\n{topic}\n\n"
                    f"## Research Context ({len(all_contexts)} sources)\n\n"
                    f"{context_block}\n\n"
                    f"Now write the complete research report."
                )
            ),
        ])

        report = response.content
        logger.info(
            "Writer generated report: %d chars, %d sources",
            len(report),
            len(source_list),
        )

        return {
            "messages": [AIMessage(content="[Writer] Research report generated successfully.")],
            "report": report,
            "sources": [
                {"title": s["title"], "url": s["url"], "type": "cited"}
                for s in source_list
            ],
            "current_agent": "supervisor",
        }

    except Exception as e:
        logger.exception("Writer agent failed: %s", e)
        return {
            "messages": [AIMessage(content=f"[Writer] Error generating report: {e!s}")],
            "report": f"# Research Report\n\nError during report generation: {e!s}",
            "current_agent": "supervisor",
        }
